In [5]:
import numpy as np

In [6]:
#Zeros Matrix

zero=np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [7]:
one=np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
#Identity matrix

idt=np.eye(3)
idt

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
#Create constant matrix

const=np.full((3,3),4)
const

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [10]:
from numpy import random

x=random.randint(10,size=(3,3))
random.seed(4)
x

array([[5, 2, 7],
       [3, 0, 0],
       [2, 5, 5]])

# ARRAY INDEXING AND SLICING

In [11]:
arr=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

 a[0][0] a[0][1] a[0][2] a[0][3]
 a[1][0] a[1][1] a[1][2] a[1][3]
 a[2][0] a[2][1] a[2][2] a[2][3]
 a[3][0] a[3][1] a[3][2] a[3][3]

In [12]:
arr[0][1]

2

In [13]:
arr[0][1]=3
arr

array([[ 1,  3,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
#Slicing
#arr[slicing of rows,slicing of columns]
#arr[st:end,st:end]

arr[1: ,1:3]

array([[ 6,  7],
       [10, 11]])

In [15]:
const=np.full((3,4),2)
const

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# ARRAY BROADCASTING

In [16]:
arr

array([[ 1,  3,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [17]:
const

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [18]:
#Addition of Matrix
print(arr+const)
print(np.add(arr,const))

[[ 3  5  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]
[[ 3  5  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


In [19]:
#Subtraction of Matrix
print(arr-const)
print(np.subtract(arr,const))

[[-1  1  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]
[[-1  1  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


In [20]:
#Multiplication of Matrix
print(arr*const)
print(np.multiply(arr,const))

[[ 2  6  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[ 2  6  6  8]
 [10 12 14 16]
 [18 20 22 24]]


In [21]:
#Division of Matrix
print(arr/const)
print(np.divide(arr,const))

[[0.5 1.5 1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]
[[0.5 1.5 1.5 2. ]
 [2.5 3.  3.5 4. ]
 [4.5 5.  5.5 6. ]]


In [22]:
#Square root

np.sqrt(const)

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

In [23]:
np.sum(arr)

79

In [24]:
np.sum(np.sqrt(const))

16.970562748477143

In [25]:
np.sum(arr,axis=0)

array([15, 19, 21, 24])

# Calculate BMI of players

In [26]:
#height of players in inches

height_in=[60,61,65,69,73,79,67,65,63,69,61]
ht_np=np.array(height_in)

#Convert into meters
ht_np=ht_np*0.0245
ht_np

array([1.47  , 1.4945, 1.5925, 1.6905, 1.7885, 1.9355, 1.6415, 1.5925,
       1.5435, 1.6905, 1.4945])

In [27]:
#Weight of players 
weight_pd=[250,235,240,245,255,265,270,280,300,230,220]
wt_np=np.array(weight_pd)

#Convert into kg
wt_np=wt_np*0.45
wt_np

array([112.5 , 105.75, 108.  , 110.25, 114.75, 119.25, 121.5 , 126.  ,
       135.  , 103.5 ,  99.  ])

In [28]:
#Calculate BMI value
bmi=wt_np/ht_np**2
bmi

array([52.06164098, 47.34657164, 42.58580621, 38.57875854, 35.87358711,
       31.83259445, 45.09148143, 49.68344058, 56.66573168, 36.21679373,
       44.32445005])

In [29]:
bmi[bmi>40]

array([52.06164098, 47.34657164, 42.58580621, 45.09148143, 49.68344058,
       56.66573168, 44.32445005])

In [30]:
players=np.array([wt_np,ht_np])
players

array([[112.5   , 105.75  , 108.    , 110.25  , 114.75  , 119.25  ,
        121.5   , 126.    , 135.    , 103.5   ,  99.    ],
       [  1.47  ,   1.4945,   1.5925,   1.6905,   1.7885,   1.9355,
          1.6415,   1.5925,   1.5435,   1.6905,   1.4945]])

In [31]:
players.shape

(2, 11)

In [32]:
pT=players.T
print(pT)
pT.shape

[[112.5      1.47  ]
 [105.75     1.4945]
 [108.       1.5925]
 [110.25     1.6905]
 [114.75     1.7885]
 [119.25     1.9355]
 [121.5      1.6415]
 [126.       1.5925]
 [135.       1.5435]
 [103.5      1.6905]
 [ 99.       1.4945]]


(11, 2)

# Statistical Operation

In [33]:
#min,max,mean,median,mode,var,std,corrcoef,perc

In [34]:
print(np.amax(ht_np))
print(np.amax(wt_np))

1.9355
135.0


In [35]:
print(np.amin(ht_np))
print(np.amin(wt_np))

1.47
99.0


In [40]:
print(np.corrcoef(ht_np,wt_np))

[[1.         0.15359728]
 [0.15359728 1.        ]]


# BOOLEAN

In [43]:
#Boolean

bools=[True,False,True,False,True]
print(bools)
b=np.array(bools)
b

[True, False, True, False, True]


array([ True, False,  True, False,  True])

In [44]:
b.sum()

3

In [45]:
b.any()

True

In [47]:
b.all()

False

In [52]:
n=np.array(['b','b','b','b','c','c'])
n

array(['b', 'b', 'b', 'b', 'c', 'c'], dtype='<U1')

In [53]:
np.unique(n)

array(['b', 'c'], dtype='<U1')