# NumPy - Numerical Python

In [7]:
#import library

import numpy as np

In [8]:
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [9]:
arr[0][2]

3

In [10]:
arr[1][2]

7

In [11]:
#dimension of array
#shape of array
#data of array
#size of array
#type of array

print(arr.ndim)
print(arr.shape)
print(arr.data)
print(arr.size)
print(type(arr))

2
(2, 4)
8
<class 'numpy.ndarray'>


# LAB-1 Random Number Generator Using Numpy



In [12]:
from numpy import random
x = random.randint(100)
x

35

In [13]:
y = random.rand(100)
y

array([0.76888058, 0.29217182, 0.58202788, 0.66811538, 0.56232825,
       0.99865516, 0.25278797, 0.12182563, 0.79504599, 0.51835784,
       0.95011561, 0.89999221, 0.39457308, 0.42923913, 0.56567785,
       0.96172202, 0.07436026, 0.66678787, 0.6524562 , 0.20263004,
       0.99114204, 0.44552504, 0.40622506, 0.1342697 , 0.15372695,
       0.93068412, 0.20010083, 0.88743908, 0.26673861, 0.06799099,
       0.36149666, 0.30115984, 0.84684267, 0.14632585, 0.1617773 ,
       0.10257405, 0.81449644, 0.2527845 , 0.07416663, 0.96001669,
       0.25900982, 0.09529327, 0.79977066, 0.44393445, 0.56606024,
       0.20787102, 0.69869829, 0.12389159, 0.87959455, 0.431812  ,
       0.03710424, 0.59798744, 0.77617933, 0.30012567, 0.37770163,
       0.65474763, 0.14978126, 0.35140068, 0.91239676, 0.62339663,
       0.53932098, 0.37559711, 0.37379049, 0.91759855, 0.42027634,
       0.71705425, 0.76905192, 0.63761634, 0.18543016, 0.52684364,
       0.74680751, 0.88109647, 0.29400112, 0.9008395 , 0.99975

In [14]:
X = random.randint(100,size=10)
X

array([97, 31, 84, 21, 66, 54, 41, 74, 76, 45])

In [15]:
Y = random.randint(100,size=(3,3))
Y

array([[90, 18, 45],
       [55,  6, 10],
       [73, 76, 42]])

In [16]:
z = random.random((2,2))
z

array([[0.60858643, 0.56141044],
       [0.75602857, 0.25562765]])

In [17]:
x = random.randint(10,size=(3,3))
random.seed(6)
x

array([[2, 7, 2],
       [1, 7, 4],
       [8, 9, 8]])

In [18]:
#zero matrix/arrays

zero = np.zeros((3,9))
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
#ones matrix/arrays

one = np.ones((5,5))
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [20]:
#identity matrix

idt = np.eye(4)
idt

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
#create a constant matrix

const = np.full((3,3),6)
const

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

# Array Indexing & Slicing

In [22]:
#indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [23]:
arr[0][0] = 6
arr

array([[ 6,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
#slicing
#arr[slicing of rows,slicing of colums]
#arr[st:end,st:end]
print(arr[1: , 1:3])
arr[0: ,0:2]

[[ 6  7]
 [10 11]]


array([[ 6,  2],
       [ 5,  6],
       [ 9, 10]])

In [25]:
const = np.full((3,4),2)
const

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

# Array Broadcasting

In [26]:
arr

array([[ 6,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [27]:
const

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [28]:
#addition of matrix
print(arr+const)
(np.add(arr,const))

[[ 8  4  5  6]
 [ 7  8  9 10]
 [11 12 13 14]]


array([[ 8,  4,  5,  6],
       [ 7,  8,  9, 10],
       [11, 12, 13, 14]])

In [29]:
#subtract of matrix
print(arr-const)
(np.subtract(arr,const))

[[ 4  0  1  2]
 [ 3  4  5  6]
 [ 7  8  9 10]]


array([[ 4,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [30]:
#multiply of matrix
print(arr*const)
(np.multiply(arr,const))

[[12  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]


array([[12,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [31]:
#square root 
sq = np.sqrt(const)
sq

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

In [32]:
np.sum(sq)

16.970562748477143

In [33]:
np.sum(sq,axis=0)

array([4.24264069, 4.24264069, 4.24264069, 4.24264069])

In [34]:
np.sum(sq,axis=1)

array([5.65685425, 5.65685425, 5.65685425])

In [35]:
np.sum(sq[0],axis=0)

5.656854249492381

# Calculate BMI Of Player


In [36]:
#height of player in inches

height_in = [61,62,53,72,78,64,80]
ht_np = np.array(height_in)
print(ht_np)

#convert into meter

ht_np = ht_np*0.0245
ht_np

[61 62 53 72 78 64 80]


array([1.4945, 1.519 , 1.2985, 1.764 , 1.911 , 1.568 , 1.96  ])

In [37]:
#weight of the player

weight_pd = [150,123,145,162,157,130,129]
wt_np = np.array(weight_pd)
print(wt_np)

#convert into kgs

wt_np =wt_np*0.45
wt_np

[150 123 145 162 157 130 129]


array([67.5 , 55.35, 65.25, 72.9 , 70.65, 58.5 , 58.05])

In [38]:
#calculate BMI

bmi = wt_np/ht_np**2
bmi

array([30.22121594, 23.98844394, 38.69872067, 23.42773844, 19.34598257,
       23.79379686, 15.1108913 ])

In [39]:
bmi[bmi<25]

array([23.98844394, 23.42773844, 19.34598257, 23.79379686, 15.1108913 ])

In [40]:
bmi[bmi>25]

array([30.22121594, 38.69872067])

In [41]:
player = np.array([wt_np,ht_np])
player

array([[67.5   , 55.35  , 65.25  , 72.9   , 70.65  , 58.5   , 58.05  ],
       [ 1.4945,  1.519 ,  1.2985,  1.764 ,  1.911 ,  1.568 ,  1.96  ]])

In [42]:
player.shape

(2, 7)

In [43]:
pT = player.T
print(pT.shape)
pT

(7, 2)


array([[67.5   ,  1.4945],
       [55.35  ,  1.519 ],
       [65.25  ,  1.2985],
       [72.9   ,  1.764 ],
       [70.65  ,  1.911 ],
       [58.5   ,  1.568 ],
       [58.05  ,  1.96  ]])

# Stastical Operation 

In [59]:
#min,max,mean,median,std,var,corrcoef,perc

print(np.amax(ht_np))
print(np.amax(wt_np))
print(np.amin(ht_np))
print(np.amin(wt_np))
print(np.mean(ht_np))
print(np.median(ht_np))
print(np.mean(wt_np))
print(np.median(wt_np))
print(np.std(ht_np))
print(np.std(wt_np))
print(np.var(ht_np))
print(np.var(wt_np))
print(np.corrcoef(ht_np,wt_np))

1.96
72.9
1.2985
55.35
1.645
1.568
64.02857142857142
65.25
0.22317817993701802
6.2986879100138875
0.04980849999999999
39.67346938775512
[[1.         0.15317667]
 [0.15317667 1.        ]]


In [60]:
#boolean

bools = [True,False,True,False,True]
print(bools)
b=np.array(bools)
b

[True, False, True, False, True]


array([ True, False,  True, False,  True])

In [61]:
b.sum()

3

In [62]:
b.all()

False

In [63]:
n=np.array(['b','b','b','b','c','c','a','a'])
n

array(['b', 'b', 'b', 'b', 'c', 'c', 'a', 'a'], dtype='<U1')

In [64]:
np.unique(n)

array(['a', 'b', 'c'], dtype='<U1')